### ISSUE TITLE
Uncaught TypeError: Cannot set property 'ss' of undefined ('strict mode')

### ISSUE THREAD

**Issue by kavika-1** [tmcw/simple-statistics#98] opened 2015-05-30 18:51 UTC
Since 'strict mode' was added in 0.9.2, encountering the following running in the browser.  Here's the output from Chrome:

Uncaught TypeError: Cannot set property 'ss' of undefined [simple_statistics.js:21]

Possible resolution: Change self execution invocation (line 1574) from

    })(this);

to

    }).call(this);

Some additional information here:
http://stackoverflow.com/questions/13865607/why-do-you-need-to-pass-in-arguments-to-a-self-executing-function-in-javascript

**Comment by tmcw** [comment] 2015-05-31 16:33
Duplicate of #93

**Closed by tmcw** 2015-05-31 16:33 UTC
